const clients = [
    {
        id: 1,
        surname: 'Горелов',
        name: 'Игорь',
        patronymic: 'Андреевич',
        isActive: true,
        registration: '29/05/2017',
        bill: 123451,
    },
    {
        id: 2,
        surname: 'Стесненко',
        name: 'Света',
        patronymic: 'Петровна',
        isActive: false,
        registration: '21/10/2001',
        bill: 123452,
    },
    {
        id: 3,
        surname: 'Кушнир',
        name: 'Олег',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '11/04/2000',
        bill: 123453,
    },
    {
        id: 4,
        surname: 'Щупова',
        name: 'Елена',
        patronymic: 'Антоновна',
        isActive: false,
        registration: '07/06/2019',
        bill: 123454,
    },
    {
        id: 5,
        surname: 'Кисленко',
        name: 'Ольга',
        patronymic: 'Владимировна',
        isActive: true,
        registration: '05/11/2012',
        bill: 123455,
    },
    {
        id: 6,
        surname: 'Звездный',
        name: 'Петр',
        patronymic: 'Андреевич',
        isActive: true,
        registration: '10/08/2012',
        bill: 123456,
    },
    {
        id: 7,
        surname: 'Иствуд',
        name: 'Андрей',
        patronymic: 'Максимович',
        isActive: true,
        registration: '15/03/2016',
        bill: 123457,
    },
    {
        id: 8,
        surname: 'Красотка',
        name: 'Анастасия',
        patronymic: 'Антоновна',
        isActive: true,
        registration: '17/12/2013',
        bill: 123458,
    },
    {
        id: 9,
        surname: 'Шевцов',
        name: 'Игорь',
        patronymic: 'Степанович',
        isActive: false,
        registration: '09/06/1997',
        bill: 123459,
    },
    {
        id: 10,
        surname: 'Солодов',
        name: 'Максим',
        patronymic: 'Филлипович',
        isActive: true,
        registration: '11/03/2019',
        bill: 123460,
    },
    {
        id: 11,
        surname: 'Шикарный',
        name: 'Андрей',
        patronymic: 'Петрович',
        isActive: true,
        registration: '15/05/2018',
        bill: 123461,
    },
    {
        id: 12,
        surname: 'Красивый',
        name: 'Владимир',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '21/12/2003',
        bill: 123462,
    },
    {
        id: 13,
        surname: 'Гордый',
        name: 'Андрей',
        patronymic: 'Степанович',
        isActive: true,
        registration: '16/07/2001',
        bill: 123463,
    },
    {
        id: 14,
        surname: 'Светлая',
        name: 'Нина',
        patronymic: 'Игоревна',
        isActive: true,
        registration: '03/07/2000',
        bill: 123464,
    },
    {
        id: 15,
        surname: 'Блонди',
        name: 'Валентина',
        patronymic: 'Федоровна',
        isActive: true,
        registration: '04/09/2012',
        bill: 123465,
    },
    {
        id: 16,
        surname: 'Севастьянов',
        name: 'Артем',
        patronymic: 'Олегович',
        isActive: true,
        registration: '12/03/2016',
        bill: 123466,
    },
    {
        id: 17,
        surname: 'Орешек',
        name: 'Света',
        patronymic: 'Сергеевна',
        isActive: true,
        registration: '22/05/2019',
        bill: 123467,
    },
    {
        id: 18,
        surname: 'Крепкий',
        name: 'Андрей',
        patronymic: 'Петрович',
        isActive: true,
        registration: '09/09/2007',
        bill: 123468,
    },
    {
        id: 19,
        surname: 'Светский',
        name: 'Максим',
        patronymic: 'Васильевич',
        isActive: false,
        registration: '04/11/2015',
        bill: 123469,
    },
    {
        id: 20,
        surname: 'Гога',
        name: 'Вячеслав',
        patronymic: 'Сергеевич',
        isActive: true,
        registration: '01/02/2013',
        bill: 123470,
    },

];
